contentColumnType: string
fieldGroup: 93f2ec11-cbb5-4967-a187-23551a82a7cb # Common
handle: photos
instructions: ''
name: Photos
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:5b4758a9-fd4d-4120-aca7-380e25fd032b' # Uploads
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add a photo'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:5b4758a9-fd4d-4120-aca7-380e25fd032b' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:5b4758a9-fd4d-4120-aca7-380e25fd032b' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
